# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('link', models.URLField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.SmallIntegerField(choices=[(1, 'OPEN'), (20, 'IN_PROGRESS'), (30, 'FINISHED')], default=1)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
